// Generated by CoffeeScript 1.8.0
(function() {
  var noteStore;

  noteStore = require('../service/noteStroe');

  noteStore.listNotebooks(function(err, books) {
    if (err) {
      return console.log(err);
    }
    return console.log(books);
  });

}).call(this);

//# sourceMappingURL=list_books.js.map
