// Generated by CoffeeScript 1.8.0
(function() {
  var async, cheerio, inlineCss, makeNote, noteStore, request, url;

  request = require('request');

  async = require('async');

  inlineCss = require('inline-css');

  cheerio = require('cheerio');

  makeNote = require('../service/makeNote');

  noteStore = require('../service/noteStroe');

  url = 'https://gist.github.com/youqingkui/cf1027f737c48bd6207d';

  request.get(url, function(err, res, body) {
    if (err) {
      return console.log(err);
    }
    return inlineCss(body, {
      url: '/'
    }, function(err2, html) {
      var $, $codeHtml, changeHtml;
      if (err2) {
        return console.log(err2);
      }
      $ = cheerio.load(html);
      $codeHtml = $(".blob-wrapper");
      $ = cheerio.load($codeHtml.html());
      $(".js-line-number").each(function(index, item) {
        var number;
        number = item.attribs['data-line-number'];
        return $(this).text(number);
      });
      $("*").map(function(i, elem) {
        var k, v, _ref, _results;
        _ref = elem.attribs;
        _results = [];
        for (k in _ref) {
          v = _ref[k];
          if (k !== 'style') {
            _results.push($(this).removeAttr(k));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
      changeHtml = $.html();
      console.log(changeHtml);
      return makeNote(noteStore, 'gist', changeHtml, '', function(err, note) {
        if (err) {
          return console.log(err);
        }
        return console.log(note);
      });
    });
  });

}).call(this);

//# sourceMappingURL=test_save.js.map
