// Generated by CoffeeScript 1.8.0
(function() {
  var async, cheerio, inlineCss, request, url;

  request = require('request');

  async = require('async');

  inlineCss = require('inline-css');

  cheerio = require('cheerio');

  url = '';

}).call(this);

//# sourceMappingURL=test_save.js.map
